sudo: false

language: python

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache
  - $HOME/.pip-cache
  - $HOME/third
  - $HOME/nltk_data

dist: xenial

matrix:
  include:
#    - python: '2.7'
#      env: TOXENV="flake8"

    - python: '2.7'
      env: TOXENV="py2.7.14-jenkins"

    - python: '3.5'
      env: TOXENV="py3.5.4-jenkins"

    - python: '3.6'
      env: TOXENV="py3.6.4-jenkins"

before_install:
  - source tools/travis/pre-install.sh # Checks Java and Python versions.

install:
  - source tools/travis/install.sh
  - source tools/travis/third-party.sh
  - pip install tox

script: tox -e $TOXENV tox.ini -vv
